name: 'DeBere Capital Partners '
favicon: null
layout_spectrum: 0.9727979281451553
typography_spectrum: 0.50609
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c5d5eb'
    - '#17100b'
    - '#d3ab9f'
    - '#684d3c'
  brandStrength: 0.3575404800940305
  lightness: 0.4029470693785697
  saturation: 0.08570645237341523
  rhythmicContrast: 0.16212502610869706
purpose: []
